apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: "vjykr/docker-nodejs"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
