apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-deploy
  namespace: default
  labels:
    app: nodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: vjykr/docker-nodejs:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  namespace: default
spec:
  type: NodePort 
  selector:
    app: nodejsapp
  ports:
  - port: 8001
    targetPort: 3000
    nodePort: 30001